$("#poem").on('pageinit', function() {

	// This page will be generated by updated Poems by Creator
});



$("#music").on('pageinit', function() {
	
	// This page is activated by the $this of the poem
});


$("#art").on('pageinit', function() {
	
	// Act on the event
});